name: update k8s pod image

on:
    workflow_dispatch:
    push:
        branches:
            - feature/CS-31

jobs:
    setup-kubeconfig:
        runs-on: ubuntu-latest
        steps:
            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
              with:
                  version: "latest"

            - name: Set up Helm
              uses: azure/setup-helm@v3
              with:
                  version: "latest"

            - name: Set up kubeconfig
              run: |
                  mkdir -p ~/.kube
                  cat <<EOF > ~/.kube/config
                  apiVersion: v1
                  kind: Config
                  clusters:
                  - cluster:
                      certificate-authority-data: ${{ secrets.K8S_CA }}
                      server: ${{ secrets.K8S_SERVER }}
                    name: github-cluster
                  contexts:
                  - context:
                      cluster: github-cluster
                      user: github-deployer
                    name: github-context
                  current-context: github-context
                  users:
                  - name: github-deployer
                    user:
                      token: ${{ secrets.K8S_TOKEN }}
                  EOF

            # - name: Helm upgrade
            #   run: |
            #       helm upgrade my-release ./my-chart --install --namespace my-namespace
            - name: update pod image
              run: |
                  kubectl rollout restart deployment backend-dev-back -n dev-back
